Add weighted 4th order non-linear estimator
mr-superonion/imPT pull request #4
Opened 2023-05-11 17:20 UTC by andyyPark

2023-05-11 20:28 UTC, mr-superonion requested changes

2023-05-12 04:33 UTC, andyyPark commented on impt/fpfs4/default.py
> +    "v0": 8,  # detection, TODO: Andy
Done!

2023-05-12 18:32 UTC, andyyPark commented on docs/examples/notebooks/1_measure_shear.ipynb
Done!

2023-05-23 12:58 UTC, mr-superonion commented on impt/fpfs4/nlobs.py
> +
https://github.com/mr-superonion/imPT/blob/main/impt/fpfs/tests/test_from_image.py
This might be a useful example

2023-05-29 13:47 UTC, andyyPark commented on impt/fpfs4/nlobs.py
> +
Added!

2023-05-29 22:49 UTC, mr-superonion approved these changes

2023-05-29 22:51 UTC, merged